theme: minima
title: MeRIT <img src="logo.png"
     style="float: left; margin-right: 10px;" />
     
description: Method Reporting with Initials for Transparency
header_pages:
  - People.md
  - Bases.md
  - FAQ.md
  - Contribute.md

