theme: minima
title: MeRIT
description: Method Reporting with Initials for Transparency
header_pages:
  - People.md
  - Bases.md
  - FAQ.md
  - Contribute.md
  avatar: "logo.png"
  round-avatar: true
  title-img: "logo.png"
